'use strict';
document.write('Truth table for Conjunction' + '<br>');
document.write('var1\tvar2\tvar1 && var2' + '<br>');
console.log('Truth table for Conjunction');
console.log('var1\tvar2\tvar1 && var2');
var var1 = true;
var var2 = true;
document.write(true + '\t' + true + '\t' + (var1 && var2) + "<br>");
document.write(true + '\t' + false + '\t' + (var1 && !var2) + "<br>");
document.write(false + '\t' + true + '\t' + (!var1 && var2) + "<br>");
document.write(false + '\t' + false + '\t' + (!var1 && !var2) + "<br>");
console.log(true + '\t' + true + '\t' + (var1 && var2));
console.log(true + '\t' + false + '\t' + (var1 && !var2));
console.log(false + '\t' + true + '\t' + (!var1 && var2));
console.log(false + '\t' + false + '\t' + (!var1 && !var2));
